/* ***************************************************************************
 * ** Copyright (c) 2012-2013 Xilinx, Inc.  All rights reserved.            **
 * **   ____  ____                                                          **
 * **  /   /\/   /                                                          **
 * ** /___/  \  /   Vendor: Xilinx                                          **
 * ** \   \   \/                                                            **
 * **  \   \                                                                **
 * **  /   /                                                                **
 * ** /___/   /\                                                            **
 * ** \   \  /  \                                                           **
 * **  \___\/\___\                                                          **
 * **                                                                       **
 * ** XILINX IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS"         **
 * ** AS A COURTESY TO YOU, SOLELY FOR USE IN DEVELOPING PROGRAMS AND       **
 * ** SOLUTIONS FOR XILINX DEVICES.  BY PROVIDING THIS DESIGN, CODE,        **
 * ** OR INFORMATION AS ONE POSSIBLE IMPLEMENTATION OF THIS FEATURE,        **
 * ** APPLICATION OR STANDARD, XILINX IS MAKING NO REPRESENTATION           **
 * ** THAT THIS IMPLEMENTATION IS FREE FROM ANY CLAIMS OF INFRINGEMENT,     **
 * ** AND YOU ARE RESPONSIBLE FOR OBTAINING ANY RIGHTS YOU MAY REQUIRE      **
 * ** FOR YOUR IMPLEMENTATION.  XILINX EXPRESSLY DISCLAIMS ANY              **
 * ** WARRANTY WHATSOEVER WITH RESPECT TO THE ADEQUACY OF THE               **
 * ** IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OR        **
 * ** REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE FROM CLAIMS OF       **
 * ** INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS       **
 * ** FOR A PARTICULAR PURPOSE.                                             **
 * **                                                                       **
 * **************************************************************************/


#ifndef __XILINX_DISPLAYPORT_TX_DRV__
#define __XILINX_DISPLAYPORT_TX_DRV__

#include "xbasic_types.h"
#include "sys_defs.h"
#include "displayport_defs.h"
#include "mode_table.h"

// TX Registers
#define XILINX_DISPLAYPORT_TX_REQUEST_TIMEOUT                (400 * SYSDEF_ONE_MICROSECOND)
#define XILINX_DISPLAYPORT_TX_CORE_ID                        (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x00FC)

//key-hole memory (64 timeslots)
#define XILINX_DISPLAYPORT_TX_VCPAYLOAD_BUFFER_ADDR          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0800)

#define XILINX_DISPLAYPORT_TX_LINK_BW_SET                    (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0000)
#define XILINX_DISPLAYPORT_TX_LANE_COUNT_SET                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0004)
#define XILINX_DISPLAYPORT_TX_ENHANCED_FRAME_EN              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0008)
#define XILINX_DISPLAYPORT_TX_TRAINING_PATTERN_SET           (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x000c)
#define XILINX_DISPLAYPORT_TX_LINK_QUAL_PATTERN_SET          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0010)
#define XILINX_DISPLAYPORT_TX_SCRAMBLING_DISABLE             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0014)
#define XILINX_DISPLAYPORT_TX_DOWNSPREAD_CTRL                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0018)
#define XILINX_DISPLAYPORT_TX_SOFT_VIDEO_RESET               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x001C)
#define XILINX_DISPLAYPORT_TX_ENABLE                         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0080)
#define XILINX_DISPLAYPORT_TX_ENABLE_MAIN_STREAM             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0084)
#define XILINX_DISPLAYPORT_TX_ENABLE_SEC_STREAM              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0088)
#define XILINX_DISPLAYPORT_TX_FORCE_SCRAMBLER_RESET          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x00C0)
#define XILINX_DISPLAYPORT_TX_CMD_REG                        (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0100)
#define XILINX_DISPLAYPORT_TX_FIFO                           (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0104)
#define XILINX_DISPLAYPORT_TX_ADDRESS_REG                    (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0108)
#define XILINX_DISPLAYPORT_TX_INTERRUPT_SIG_STATE            (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0130)
#define XILINX_DISPLAYPORT_TX_INTERRUPT                      (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0140)
#define XILINX_DISPLAYPORT_TX_INTERRUPT_MASK                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0144)
#define XILINX_DISPLAYPORT_TX_CLK_DIVIDER                    (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x010C)
#define XILINX_DISPLAYPORT_TX_STATUS                         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0130)
#define XILINX_DISPLAYPORT_TX_RCV_FIFO                       (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0134)
#define XILINX_DISPLAYPORT_TX_RCV_REPLY_REG                  (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0138)
#define XILINX_DISPLAYPORT_TX_RCV_REPLY_COUNT                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x013C)
#define XILINX_DISPLAYPORT_TX_RCV_DATA_COUNT                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0148)
#define XILINX_DISPLAYPORT_TX_AUX_TRANSACTION_STATUS         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x014C)

#define XILINX_DISPLAYPORT_TX_AUDIO_CONTROL                  (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0300)
#define XILINX_DISPLAYPORT_TX_AUDIO_CHANNELS                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0304)
#define XILINX_DISPLAYPORT_TX_AUDIO_INFO_DATA                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0308)
#define XILINX_DISPLAYPORT_TX_AUDIO_MAUD                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0328)
#define XILINX_DISPLAYPORT_TX_AUDIO_NAUD                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x032C)
//0x330-0x350
#define XILINX_DISPLAYPORT_TX_AUDIO_EXT_DATA                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0330)

// Main Link registers                                           
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HTOTAL               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0180)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VTOTAL               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0184)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_POLARITY             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0188)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSWIDTH              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x018C)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSWIDTH              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0190)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HRES                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0194)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VRES                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0198)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSTART               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x019C)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSTART               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01A0)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC0                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01A4)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC1                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01A8)
#define XILINX_DISPLAYPORT_TX_M_VID                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01AC)
#define XILINX_DISPLAYPORT_TX_TRANSFER_UNIT_SIZE             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01B0)
#define XILINX_DISPLAYPORT_TX_N_VID                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01B4)
#define XILINX_DISPLAYPORT_TX_USER_PIXEL_WIDTH               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01B8)
#define XILINX_DISPLAYPORT_TX_DATA_PER_LANE                  (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01BC)
#define XILINX_DISPLAYPORT_TX_INTERLACED                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01C0)
#define XILINX_DISPLAYPORT_TX_MIN_BYTES_PER_TU               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01C4)
#define XILINX_DISPLAYPORT_TX_FRAC_BYTES_PER_TU              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01C8)
#define XILINX_DISPLAYPORT_TX_INIT_WAIT                      (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x01CC)

#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HTOTAL_STREAM2               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0500)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VTOTAL_STREAM2               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0504)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_POLARITY_STREAM2             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0508)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSWIDTH_STREAM2              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x050C)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSWIDTH_STREAM2              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0510)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HRES_STREAM2                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0514)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VRES_STREAM2                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0518)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSTART_STREAM2               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x051C)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSTART_STREAM2               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0520)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC0_STREAM2                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0524)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC1_STREAM2                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0528)
#define XILINX_DISPLAYPORT_TX_M_VID_STREAM2                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x052C)
#define XILINX_DISPLAYPORT_TX_TRANSFER_UNIT_SIZE_STREAM2             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0530)
#define XILINX_DISPLAYPORT_TX_N_VID_STREAM2                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0534)
#define XILINX_DISPLAYPORT_TX_USER_PIXEL_WIDTH_STREAM2               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0538)
#define XILINX_DISPLAYPORT_TX_DATA_PER_LANE_STREAM2                  (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x053C)
#define XILINX_DISPLAYPORT_TX_INTERLACED_STREAM2                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0540)
#define XILINX_DISPLAYPORT_TX_MIN_BYTES_PER_TU_STREAM2               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0544)
#define XILINX_DISPLAYPORT_TX_FRAC_BYTES_PER_TU_STREAM2              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0548)
#define XILINX_DISPLAYPORT_TX_INIT_WAIT_STREAM2                      (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x054C)

#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HTOTAL_STREAM3               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0550)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VTOTAL_STREAM3               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0554)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_POLARITY_STREAM3             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0558)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSWIDTH_STREAM3              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x055C)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSWIDTH_STREAM3              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0560)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HRES_STREAM3                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0564)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VRES_STREAM3                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0568)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSTART_STREAM3               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x056C)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSTART_STREAM3               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0570)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC0_STREAM3                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0574)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC1_STREAM3                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0578)
#define XILINX_DISPLAYPORT_TX_M_VID_STREAM3                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x057C)
#define XILINX_DISPLAYPORT_TX_TRANSFER_UNIT_SIZE_STREAM3             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0580)
#define XILINX_DISPLAYPORT_TX_N_VID_STREAM3                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0584)
#define XILINX_DISPLAYPORT_TX_USER_PIXEL_WIDTH_STREAM3               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0588)
#define XILINX_DISPLAYPORT_TX_DATA_PER_LANE_STREAM3                  (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x058C)
#define XILINX_DISPLAYPORT_TX_INTERLACED_STREAM3                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0590)
#define XILINX_DISPLAYPORT_TX_MIN_BYTES_PER_TU_STREAM3               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0594)
#define XILINX_DISPLAYPORT_TX_FRAC_BYTES_PER_TU_STREAM3              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0598)
#define XILINX_DISPLAYPORT_TX_INIT_WAIT_STREAM3                      (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x059C)

#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HTOTAL_STREAM4               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05A0)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VTOTAL_STREAM4               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05A4)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_POLARITY_STREAM4             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05A8)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSWIDTH_STREAM4              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05AC)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSWIDTH_STREAM4              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05B0)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HRES_STREAM4                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05B4)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VRES_STREAM4                 (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05B8)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_HSTART_STREAM4               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05BC)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_VSTART_STREAM4               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05C0)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC0_STREAM4                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05C4)
#define XILINX_DISPLAYPORT_TX_MAIN_LINK_MISC1_STREAM4                (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05C8)
#define XILINX_DISPLAYPORT_TX_M_VID_STREAM4                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05CC)
#define XILINX_DISPLAYPORT_TX_TRANSFER_UNIT_SIZE_STREAM4             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05D0)
#define XILINX_DISPLAYPORT_TX_N_VID_STREAM4                          (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05D4)
#define XILINX_DISPLAYPORT_TX_USER_PIXEL_WIDTH_STREAM4               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05D8)
#define XILINX_DISPLAYPORT_TX_DATA_PER_LANE_STREAM4                  (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05DC)
#define XILINX_DISPLAYPORT_TX_INTERLACED_STREAM4                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05E0)
#define XILINX_DISPLAYPORT_TX_MIN_BYTES_PER_TU_STREAM4               (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05E4)
#define XILINX_DISPLAYPORT_TX_FRAC_BYTES_PER_TU_STREAM4              (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05E8)
#define XILINX_DISPLAYPORT_TX_INIT_WAIT_STREAM4                      (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x05EC)

// PHY registers
#define XILINX_DISPLAYPORT_TX_PHY_RESET                      (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0200)
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_LANE_0         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0210)
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_LANE_1         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0214)
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_LANE_2         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0218)
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_LANE_3         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x021C)
#define XILINX_DISPLAYPORT_TX_PHY_VOLTAGE_DIFF_LANE_0        (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0220)
#define XILINX_DISPLAYPORT_TX_PHY_VOLTAGE_DIFF_LANE_1        (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0224)
#define XILINX_DISPLAYPORT_TX_PHY_VOLTAGE_DIFF_LANE_2        (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0228)
#define XILINX_DISPLAYPORT_TX_PHY_VOLTAGE_DIFF_LANE_3        (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x022C)
#define XILINX_DISPLAYPORT_TX_PHY_TRANSMIT_PRBS7             (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0230)
#define XILINX_DISPLAYPORT_TX_PHY_CLOCK_FEEDBACK_SETTING     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0234)
#define XILINX_DISPLAYPORT_TX_PHY_POWER_DOWN                 (XILINX_DISPLAYPORT_RX_BASE_ADDRESS + 0x0238)
#define XILINX_DISPLAYPORT_TX_PHY_STATUS                     (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0280)

#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_LANE_0         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x023C)
#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_LANE_1         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0240)
#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_LANE_2         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0244)
#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_LANE_3         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0248)

#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_LANE_0         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x024C)
#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_LANE_1         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0250)
#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_LANE_2         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0254)
#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_LANE_3         (XILINX_DISPLAYPORT_TX_BASE_ADDRESS + 0x0258)


#define XILINX_DISPLAYPORT_TX_PHY_VSWING_0                   0x3 //0x06  400/400
#define XILINX_DISPLAYPORT_TX_PHY_VSWING_1                   0x7 //      600/600
#define XILINX_DISPLAYPORT_TX_PHY_VSWING_2                   0xB //0x04  800/800
#define XILINX_DISPLAYPORT_TX_PHY_VSWING_3                   0xf //0x00  1200/1000

#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_0              0x0  // 0x01 //      0.0db
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_1              0x3  // 0x02 3.5db
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_2              0x5  // 0x03 6.0db (6.1)
#define XILINX_DISPLAYPORT_TX_PHY_PREEMPHASIS_3              0x6  // 0x04 9.5db (7.6)

#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_0              0x0  // 0x01 //      0.0db
#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_1              0xE  // 0x02 3.5db
#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_2              0x14  // 0x03 6.0db (6.1)
#define XILINX_DISPLAYPORT_TX_PHY_POSTCURSOR_3              0x1B  // 0x04 9.5db (7.6)

#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_0              0x0  // 0x01 //      0.0db
#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_1              0x0  // 0x02 3.5db
#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_2              0x0  // 0x03 6.0db (6.1)
#define XILINX_DISPLAYPORT_TX_PHY_PRECURSOR_3              0x0  // 0x04 9.5db

#define XILINX_DISPLAYPORT_TX_PHY_CLK_FB_540                 0x05
#define XILINX_DISPLAYPORT_TX_PHY_CLK_FB_270                 0x03
#define XILINX_DISPLAYPORT_TX_PHY_CLK_FB_162                 0x01
// TX AUX status constants
#define XILINX_DISPLAYPORT_TX_AUX_HPD                        0x01 // Bit 0
#define XILINX_DISPLAYPORT_TX_AUX_REQUEST_IN_PROGRESS        0x02 // Bit 1
#define XILINX_DISPLAYPORT_TX_AUX_REPLY_RECEIVED             0x04 // Bit 2
#define XILINX_DISPLAYPORT_TX_AUX_REPLY_TIMEOUT              0x08 // Bit 3

// function prototypes
       UINT32 dptx_init(void);
       UINT32 dptx_set_clkspeed(UINT32 speed);
       UINT32 dptx_tx_ready(void);
         void dptx_enable(Xboolean enable);
       UINT32 dptx_send_request( XILDPAUXTransaction *req );
       UINT32 dptx_read_reply(Xboolean is_read, UINT32 byte_count, XILDPAUXTransaction *reply);
         void dptx_dump_regs(void);
       UINT32 dptx_wait_reply(void);
       UINT32 dptx_wait_phy_ready(void);
       
      UINT32 dptx_reg_read(UINT32 reg_address);
      void dptx_reg_write(UINT32 reg_address, UINT32 data);
       UINT32 dptx_iic_read(UINT32 device_address, UINT32 reg_address, UINT32 byte_count, UINT8 *data_buffer);
       UINT32 dptx_iic_read_transaction(UINT32 device_address, UINT32 reg_address, UINT8 *data_buffer, UINT8 byte_count);
         void dptx_iic_write(UINT32 device_address, UINT32 reg_address, UINT32 write_data);
      UINT32 dptx_get_reply_code(void);

       // interrupt service handler declaration
       UINT32 dptx_isr(UINT32 arg0, void *isr_data);

       UINT32 dptx_main_link_enable(void);
       UINT32 dptx_main_link_config(DisplayMode *dm);

       UINT32 dptx_set_user_data_count(UINT32 hres, UINT32 bytes_per_pixel, UINT32 lane_count);

#endif /* __XILINX_DISPLAYPORT_TX_DRV__ */
